# SPDX-FileCopyrightText: (C) 2021 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

different-formats-maps-api: # NEX-T10392-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_different_formats_maps_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)

persistence-api: # NEX-T10393-API
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)

	$(eval PROJECT := persistence-api)
	$(eval CLEANUP_MODE := keep_volumes)
	$(eval SKIP_INIT := 0)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_persistence_on_page_navigate_api.py, 'pgserver web', true, /run/secrets/controller.auth)

	$(eval PROJECT := persistence-api)
	$(eval CLEANUP_MODE := full)
	$(eval SKIP_INIT := 1)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_persistence_on_restart_api.py, 'pgserver web', true, /run/secrets/controller.auth)

	$(eval SECRETSDIR := $(OLDSECRETSDIR))
	$(eval PROJECT :=)
	$(eval CLEANUP_MODE :=)
	$(eval SKIP_INIT :=)

additional-floor-plans-api: # NEX-T10405-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_additional_floor_plans_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)

scene-import-api: # NEX-T13967
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_scene_import_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

scene-import-json: # NEX-T15347
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/scene_no_db.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_scene_import_json.py, 'scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

scenes-summary-api: # NEX-T10394-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_scenes_summary_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

scene-details-api: # NEX-T10395-API
	$(eval SERVICES := $(strip pgserver web retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/cams.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_scene_details_api.py, '$(SERVICES)', true, /run/secrets/controller.auth)

object-crud-api: # NEX-T10429-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_object_crud_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)

add-delete-3d-object-api: # NEX-T10428-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_add_delete_3d_object_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)

upload-3d-glb-file-api: # NEX-T10425-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_upload_3d_glb_file_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)

upload-only-3d-glb-files-api: # NEX-T10433-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_upload_only_3d_glb_files_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)

sensor-area-api: # NEX-T10401-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_sensor_area_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

superuser-crud-operations-api: # NEX-T10418-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_superuser_crud_operations_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

sensor-location-api: # NEX-T10400-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_sensor_location_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

sensor-scene-api: # NEX-T10396
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_sensor_scene_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

calibrate-all-sensor-types-api: # NEX-T10457-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_calibrate_all_sensor_types_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)

add-orphaned-cameras: # NEX-T10402
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_add_orphaned_cameras.py, 'pgserver web scene', true, /run/secrets/controller.auth)

api-large-strings: # NEX-T10583
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_api_large_strings.py, 'pgserver web scene', true, /run/secrets/controller.auth)

auto-calibration:  # NEX-T10405
	$(eval SERVICES := $(strip pgserver web queuing-video autocalibration))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web_calibration.yml:$(COMPOSE)/dlstreamer/queuing_video.yml:$(COMPOSE)/autocalibration.yml:$(COMPOSE)/cams.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_auto_calibration.py, '$(SERVICES)', true, /run/secrets/browser.auth,tests/calibrationdb.tar.bz2)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

child-scenes: # NEX-T10439
	$(eval IMAGE_OLD := $(BASE_IMAGE))
	$(eval override BASE_IMAGE := $(IMAGE)-controller-test)
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_child_scenes.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval override BASE_IMAGE := $(IMAGE_OLD))

camera-deletion-api: # NEX-T10403-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_camera_deletion_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

camera-intrinsics-api: # NEX-T10415-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_camera_intrinsics_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

delete-roi-mqtt: # NEX-T10430
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_delete_roi_mqtt.py, 'pgserver scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

delete-sensor-mqtt-api: # NEX-T10432-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_delete_sensor_mqtt_api.py, 'pgserver scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

delete-sensor-scene-api: # NEX-T10397-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_delete_sensor_scene_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

delete-sensors-api: # NEX-T10399-API
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_delete_sensors_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

delete-tripwire-mqtt: # NEX-T10431
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_delete_tripwire_mqtt.py, 'pgserver scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

geospatial-ingest-publish: # NEX-T10490
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_geospatial_ingest_publish.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

manual-camera-calibration-api: # NEX-15280
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_manual_camera_calibration_api.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

mqtt-auth: # NEX-T10423
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/security/system/negative_mqtt_insecure_auth.py)

mqtt-cert: # NEX-T10423
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/security/system/negative_mqtt_insecure_cert.py)

mqtt-roi: # NEX-T10404
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_roi_mqtt.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

mqtt-sensor-roi: # NEX-T10460
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_mqtt_sensor_roi.py, 'pgserver web scene', true, /run/secrets/controller.auth)

mqtt-slow-sensor-roi: # NEX-T10461
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_mqtt_slow_sensor_roi.py, 'pgserver web scene', true, /run/secrets/controller.auth)

mqtt-tripwire: # NEX-T10406
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_tripwire_mqtt.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

out-of-box: # NEX-T10417
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/dlstreamer/queuing_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web_default.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/cams.yml)
	$(eval SERVICES := $(strip pgserver web queuing-video retail-video scene))
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_out_of_box.py, '$(SERVICES)', true, /run/secrets/browser.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))


out-of-box-no-ntp: # NEX-T10417
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video_no_ntp.yml:$(COMPOSE)/dlstreamer/queuing_video_no_ntp.yml:$(COMPOSE)/scene_no_ntp.yml:$(COMPOSE)/web_default.yml:$(COMPOSE)/cams.yml)
	$(eval SERVICES := $(strip pgserver web queuing-video retail-video scene))
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_out_of_box.py, '$(SERVICES)', true, /run/secrets/browser.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

orphaned-sensor: # NEX-T10398
	$(call set-prefix)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_orphaned_sensor.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

reid-performance-degradation: # NEX-T10541
	$(eval SERVICES := $(strip pgserver web queuing-video retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/vdms.yml:$(COMPOSE)/dlstreamer/retail_video_reid.yml:$(COMPOSE)/dlstreamer/queuing_video_reid.yml:$(COMPOSE)/scene_reid.yml:$(COMPOSE)/web_default.yml:$(COMPOSE)/cams.yml)
	$(eval override IMAGE_OLD := $(BASE_IMAGE))
	$(eval BASE_IMAGE := $(IMAGE)-controller-test)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_reid_performance_degradation.py, '$(SERVICES)', true)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))
	$(eval override BASE_IMAGE := $(IMAGE_OLD))

reid-unique-count: # NEX-T10539
	$(eval SERVICES := $(strip pgserver web queuing-video retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/vdms.yml:$(COMPOSE)/dlstreamer/retail_video_reid.yml:$(COMPOSE)/dlstreamer/queuing_video_reid.yml:$(COMPOSE)/scene_reid.yml:$(COMPOSE)/web_default.yml:$(COMPOSE)/cams.yml)
	$(eval override IMAGE_OLD := $(BASE_IMAGE))
	$(eval BASE_IMAGE := $(IMAGE)-controller-test)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_reid_unique_count.py, '$(SERVICES)', true)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))
	$(eval override BASE_IMAGE := $(IMAGE_OLD))

rest-test: # NEX-T10464
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_rest_test.py, 'pgserver web', true, /run/secrets/controller.auth)

scene-import: # NEX-T13051
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/cams.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_scene_import.py, 'pgserver web retail-video scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

sensors-send-events: # NEX-T10456
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_sensors_send_mqtt_messages.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

vdms-similarity-search: # NEX-T10516
	$(eval override IMAGE_OLD := $(BASE_IMAGE))
	$(eval override BASE_IMAGE := $(IMAGE)-controller-test)
	$(call common-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/vdms.yml:$(COMPOSE)/pgserver.yml, tests/functional/tc_vdms_similarity_search.py,'pgserver',true, /run/secrets/controller.auth)
	$(eval override BASE_IMAGE := $(IMAGE_OLD))

dlstreamer-api: # NEX-T12678
	$(eval SERVICES := $(strip pgserver web queuing-video retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/dlstreamer/queuing_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/cams.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_dlstreamer_api.py, '$(SERVICES)', true, /run/secrets/browser.auth)
