# SPDX-FileCopyrightText: (C) 2021 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

SSCAPE_TESTS_PATH=tests/sscape_tests

define unit-docker-compose-recipe=
	$(eval TEST_FOLDER=$1)
	$(eval YML_FILENAME=$2)
	$(eval TEST_IMAGE=$3)
	$(eval DBROOT=$(TEST_DATA)/db_$@)
	$(eval LOGFILE=$(TEST_DATA)/unit/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
	  ; echo RUNNING TEST $@ \
	  ; cd .. \
	  ; mkdir -p $(shell dirname $(LOGFILE)) \
	  ; $(SSCAPE_TESTS_PATH)/secrets.sh \
	  ; env SECRETSDIR=$(SECRETSDIR) IMAGE=$(TEST_IMAGE):$(VERSION) DBROOT=$(DBROOT) $(RUNTEST) $(YML_FILENAME) \
	  $(UNIT_TEST_COVERAGE_CMD) --source=sscape/ -m pytest -s $(GENERATE_JUNITXML_UNITTEST) $(SSCAPE_TESTS_PATH)/$(TEST_FOLDER)/ 2>&1 | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@
endef

define unit-recipe=
	$(eval TEST_FOLDER=$1)
	$(eval DOCKER_IMAGE=$2)
	$(eval DOCKER_IMAGE=$(if $(DOCKER_IMAGE), $(DOCKER_IMAGE), $(IMAGE)))
	$(eval LOGFILE=$(TEST_DATA)/unit/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
	  ; echo RUNNING TEST $@ \
	  ; cd .. \
	  ; mkdir -p $(shell dirname $(LOGFILE)) \
	  ; $(SSCAPE_TESTS_PATH)/secrets.sh \
	  ; tools/scenescape-start --image $(DOCKER_IMAGE) sh -c "export PYTHONPATH=/home/scenescape/SceneScape/ && $(UNIT_TEST_COVERAGE_CMD) --source=sscape/ -m pytest -s $(GENERATE_JUNITXML_UNITTEST) $(SSCAPE_TESTS_PATH)/$(TEST_FOLDER)/" 2>&1 | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@
endef

# Recipes below must be in alphabetical order

autocamcalib-unit: # NEX-T10459
	$(call unit-recipe, autocamcalib, $(IMAGE)-autocalibration-test)

account-security-unit:
	$(call unit-recipe, account-security, $(IMAGE)-manager-test)

cam-unit:
	$(call unit-recipe, cam, $(IMAGE)-manager-test)

geometry-unit: # NEX-T10454
	$(call unit-recipe, geometry, $(IMAGE)-manager-test)

geospatial-unit: # NEX-T10490
	$(call unit-recipe, geospatial, $(IMAGE)-manager-test)

markerless-unit: # NEX-T10497
	$(call unit-docker-compose-recipe, markerless, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/web.yml:$(COMPOSE)/autocalibration.yml, $(IMAGE)-autocalibration-test)

mesh-util-unit:
	$(call unit-recipe, mesh_util, $(IMAGE)-controller-test)

robot-vision-unit:
	$(call unit-recipe, robot_vision, $(IMAGE)-controller-test)

scene-unit: # NEX-T10451
	$(call unit-recipe, scene_pytest, $(IMAGE)-controller-test)

scenescape-unit: # NEX-T10450
	$(call unit-recipe, scenescape, $(IMAGE)-manager-test)

schema-unit: # NEX-T10458
	$(call unit-recipe, schema, $(IMAGE)-manager-test)

singleton-sensor-unit:
	$(call unit-recipe, singleton_sensor, $(IMAGE)-manager-test)

timestamp-unit: # NEX-T10480
	$(call unit-recipe, timestamp, $(IMAGE)-manager-test)

transform-unit: # NEX-T10512
	$(call unit-recipe, transform, $(IMAGE)-manager-test)

views-unit: # NEX-T10479
	$(call unit-recipe, views, $(IMAGE)-manager-test)
