#!/bin/bash

# SPDX-FileCopyrightText: (C) 2021 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
echo "Starting webserver-init script"

# Set HOME environment variable for Apache to prevent library issues
export HOME=${WSHOME}
echo "export HOME=${WSHOME}" >> /etc/apache2/envvars

cd ${MANAGERDIR}

mkdir -p ${MANAGERDIR}/media/
cp -n ${DBROOT}/media/* ${MANAGERDIR}/media/
# Remove symlink and make a copy
rm -f ${MANAGERDIR}/manager/secrets.py
cp ${RUNSECRETS}/django/secrets.py ${MANAGERDIR}/manager/secrets.py

if [ -d "${MANAGERDIR}/models" ] ; then
    chmod -R a+rX "${MANAGERDIR}/models"
fi

if [ -n "${BROKER}" ] ; then
    echo "${BROKER}" | awk '{printf "export BROKER=%s\n", $2}' >> /etc/apache2/envvars
fi
if [ -z "${BROKERAUTH}" ] ; then
    BROWSERAUTH=$(fgrep BROWSER_AUTH_FILE ${MANAGERDIR}/manager/settings.py \
                    | awk '{print $3}' | sed -e 's/"//g')
    # If default auth file is in /run/secrets, need to make a copy
    # that www-data can read
    if [[ "${BROWSERAUTH}" == /run/secrets/* ]] ; then
        BROKERAUTH=${BROWSERAUTH}
    fi
fi
if [ -n "${BROKERAUTH}" ] ; then
    BAUTHFILE=${WSHOME}/$(basename ${BROKERAUTH})
    cp ${BROKERAUTH} ${BAUTHFILE}
    echo "export BROKERAUTH=${BAUTHFILE}" >> /etc/apache2/envvars
fi

# Handle broker root cert
if [ -z "${BROKERROOTCERT}" ] ; then
    ROOTCERT=$(fgrep ROOT_CERT_FILE ${MANAGERDIR}/manager/settings.py \
                    | awk '{print $3}' | sed -e 's/"//g')
    # If default root cert file is in /run/secrets, need to make a copy
    # that www-data can read
    if [[ "${ROOTCERT}" == /run/secrets/* ]] ; then
        BROKERROOTCERT=${ROOTCERT}
    fi
fi
if [ -n "${BROKERROOTCERT}" ] ; then
    CERTFILE=${WSHOME}/$(basename ${BROKERROOTCERT})
    cp ${BROKERROOTCERT} ${CERTFILE}
    echo "export BROKERROOTCERT=${CERTFILE}" >> /etc/apache2/envvars
fi

# In Kubernetes, serve the /mqtt proxy on port 80 as well, to use behind reverse proxies
if [ -n "${KUBERNETES_SERVICE_HOST}" ] ; then
    sed -i '/<\/VirtualHost>/i \
    SSLProxyEngine on \
    ProxyPass /mqtt wss://broker.scenescape.intel.com:1884/ \
    ProxyPassReverse /mqtt wss://broker.scenescape.intel.com:1884/ \
    ProxyPass /v1/ https://autocalibration.scenescape.intel.com:8443/v1/ \
    ProxyPassReverse /v1/ https://autocalibration.scenescape.intel.com:8443/v1/ \
    ProxyPass "/socket.io/" "wss://autocalibration.scenescape.intel.com:8443/socket.io/" \
    ProxyPassReverse "/socket.io/" "wss://autocalibration.scenescape.intel.com:8443/socket.io/" \
    \n        WSGIPassAuthorization On' /etc/apache2/sites-available/000-default.conf
fi

# Change broker ProxyPass in default-ssl.conf to be dynamic
HOST=$(echo ${BROKER} | awk '{printf "%s\n", $2}')
HOST=${HOST:-broker.scenescape.intel.com}
if [[ ${HOST} == *":"* ]]; then
    sed -i "s/broker.scenescape.intel.com:1884/${HOST}/g" /etc/apache2/sites-available/default-ssl.conf
    sed -i "s/broker.scenescape.intel.com:1884/${HOST}/g" /etc/apache2/sites-available/000-default.conf
else
    sed -i "s/broker.scenescape.intel.com/${HOST}/g" /etc/apache2/sites-available/default-ssl.conf
    sed -i "s/broker.scenescape.intel.com/${HOST}/g" /etc/apache2/sites-available/000-default.conf
fi

if [ -n "${AUTOCALIBRATION}" ] ; then
    echo "${AUTOCALIBRATION}" | awk '{printf "export AUTOCALIBRATION=%s\n", $2}' >> /etc/apache2/envvars
fi
AUTOCALIBRATION_HOST=$(echo ${AUTOCALIBRATION} | awk '{printf "%s\n", $2}')
AUTOCALIBRATION_HOST=${AUTOCALIBRATION_HOST:-autocalibration.scenescape.intel.com}
if [[ ${AUTOCALIBRATION_HOST} == *":"* ]]; then
    sed -i "s/autocalibration.scenescape.intel.com:8443/${AUTOCALIBRATION_HOST}/g" /etc/apache2/sites-available/default-ssl.conf
    sed -i "s/autocalibration.scenescape.intel.com:8443/${AUTOCALIBRATION_HOST}/g" /etc/apache2/sites-available/000-default.conf
else
    sed -i "s/autocalibration.scenescape.intel.com/${AUTOCALIBRATION_HOST}/g" /etc/apache2/sites-available/default-ssl.conf
    sed -i "s/autocalibration.scenescape.intel.com/${AUTOCALIBRATION_HOST}/g" /etc/apache2/sites-available/000-default.conf
fi


echo Running interface
apache2ctl -D FOREGROUND &
WAITPID="${WAITPID} $!"
set --
